//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.02 at 11:03:14 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.companyinfo.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.companyinfo;
