//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140802.1033 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.04 at 12:34:54 PM CET 
//


package com.applicationschema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.applicationschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.applicationschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CourseTranscript }
     * 
     */
    public CourseTranscript createCourseTranscript() {
        return new CourseTranscript();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link Workhistorytype }
     * 
     */
    public Workhistorytype createWorkhistorytype() {
        return new Workhistorytype();
    }

    /**
     * Create an instance of {@link Schoolprogram }
     * 
     */
    public Schoolprogram createSchoolprogram() {
        return new Schoolprogram();
    }

}
